theme: jekyll-theme-slate



navigation:
  - {file: "people.md", title: "People", icon: people}
  - {file: "calendar", title: "Calendar", icon: calendar}
  - {file: "README.md", title: "Home", icon: home}
  
#external:
#  - {title: Mail, icon: people}
#  - {title: Twitter, icon: calendar}
#  - {title: Home, icon: home}
